fieldLayouts:
  fe21c3d0-27f4-4678-b135-2dca5f0aaaf3:
    tabs:
      -
        elements:
          -
            autocapitalize: true
            autocomplete: false
            autocorrect: true
            class: null
            disabled: false
            id: null
            instructions: null
            label: null
            max: null
            min: null
            name: null
            orientation: null
            placeholder: null
            readonly: false
            requirable: false
            size: null
            step: null
            tip: null
            title: null
            type: craft\fieldlayoutelements\entries\EntryTitleField
            uid: 754f2c5f-1a32-49b7-9b61-9e3ffc498400
            warning: null
            width: 100
          -
            fieldUid: f0bec9e7-a644-4b58-8dee-e8bbd601c12f # introSpellen
            instructions: null
            label: null
            required: false
            tip: null
            type: craft\fieldlayoutelements\CustomField
            uid: 0c878260-6437-4e22-9b51-660e596b4ebf
            warning: null
            width: 100
        name: Content
        uid: 9636a9c8-5fd8-4dd1-adc0-714d9d544dda
handle: default
hasTitleField: true
name: Default
section: abe62c05-5496-4048-b7ff-3c1e7caf8f8a # Al onze spellen
sortOrder: 1
titleFormat: null
titleTranslationKeyFormat: null
titleTranslationMethod: site
