columnSuffix: null
contentColumnType: string
fieldGroup: e668e463-a178-46d0-8816-43214a2ee2e9 # spellen
handle: minimumLeeftijd
instructions: null
name: 'minimum leeftijd'
searchable: false
settings:
  allowLimit: false
  allowMultipleSources: false
  allowSelfRelations: false
  branchLimit: null
  localizeRelations: false
  maxRelations: null
  minRelations: null
  selectionLabel: null
  showSiteMenu: false
  source: 'group:8baf006e-dc14-4e65-b634-adf4f3f7dd95' # Minimum leeftijd
  sources: '*'
  targetSiteId: null
  validateRelatedElements: false
  viewMode: null
translationKeyFormat: null
translationMethod: site
type: craft\fields\Categories
