columnSuffix: vjheypha
contentColumnType: text
fieldGroup: e668e463-a178-46d0-8816-43214a2ee2e9 # spellen
handle: minimumLeeftijdAge
instructions: null
name: 'minimum leeftijd'
searchable: false
settings:
  byteLimit: null
  charLimit: null
  code: false
  columnType: null
  initialRows: 4
  multiline: false
  placeholder: null
  uiMode: normal
translationKeyFormat: null
translationMethod: none
type: craft\fields\PlainText
