defaultPlacement: end
enableVersioning: true
handle: alOnzeSpellen
name: 'Al onze spellen'
previewTargets:
  -
    __assoc__:
      -
        - label
        - 'Primary entry page'
      -
        - urlFormat
        - '{url}'
      -
        - refresh
        - '1'
propagationMethod: all
siteSettings:
  aa670809-9a9d-4ecd-91ae-7ea0e9e17f29: # Examen Web Expert 2
    enabledByDefault: true
    hasUrls: true
    template: _boardgames/_index.twig
    uriFormat: games
type: channel
